# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: winter.forum::lang.channels.name

# Model Form Field configuration
form: ~/plugins/winter/forum/models/channel/fields.yaml

# Model Class name
modelClass: Winter\Forum\Models\Channel

# Default redirect location
defaultRedirect: winter/forum/channels

# Create page
create:
    title: winter.forum::lang.channels.create
    redirect: winter/forum/channels/update/:id
    redirectClose: winter/forum/channels

# Update page
update:
    title: winter.forum::lang.channels.update
    redirect: winter/forum/channels
    redirectClose: winter/forum/channels

# Preview page
preview:
    title: winter.forum::lang.channels.preview